services:
  - type: web
    name: shopease
    runtime: python
    plan: free
    rootDir: ShopEase-Django
    buildCommand: bash build.sh
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "0"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: shopease-db
          property: connectionString

databases:
  - name: shopease-db
    plan: free
    databaseName: shopease
    user: shopease
